spring.application.name=interviewPrep

spring.datasource.url=jdbc:mysql://localhost:3306/testDb
spring.datasource.username=root
spring.datasource.password=Khalasi@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
